### ISSUE TITLE
[NumberGuesser] Ругательства

### ISSUE THREAD

**Issue by pavel-b-novikov** [Carrybubbles/nsudotnet#1]
Сделайте более разнообразные ругательства. У вас же столько инструментов

**Comment by Carrybubbles** [comment]
Добавил еще пару ругательств.

**Comment by pavel-b-novikov** [comment]
Вы неправильно поняли. Я хочу чтобы имя пользователя появлялось не на фиксированном месте ругательства, а чтобы на разных.

**Comment by Carrybubbles** [comment]
Done

**Comment by pavel-b-novikov** [comment]
``` var pos = phrase.IndexOf(" ", randomGenerator.Next() % phrase.Length);```
Да что ж вы такое несете...

string.Format!!

**Comment by Carrybubbles** [comment]
Как-то так.
` int namePos = randomGenerator.Next(0,2);`
  `if (namePos == 0)`
  `{`
  `        Console.WriteLine(phrase, name,string.Empty);`
  `}`
  `else if(namePos == 1)`
  `{`
  `   Console.WriteLine(phrase, string.Empty, name);`
  ` }`

**Comment by pavel-b-novikov** [comment]
А вы не можете просто распихать {0} на разные места в ругательствах?

**Comment by Carrybubbles** [comment]
исправил

**Comment by pavel-b-novikov** [comment]
Бегите и больше мне на глаза не попадайтесь
