### ISSUE TITLE
[LinesCounter] Новые строки

### ISSUE THREAD

**Issue by pavel-b-novikov** [Carrybubbles/nsudotnet#4]
Пожалуйста, оцените сколько новых строк вы создаете в ходе решения задачи

**Comment by Carrybubbles** [comment]
Действительно, создавал лишние строки, поэтому заменил string.replace() на StringBuilder.repalce()
String.Replace()
// This method contains the same functionality as StringBuilder Replace. The only difference is that
// a new String has to be allocated since Strings are immutable

**Comment by pavel-b-novikov** [comment]
Зачем вам блин вообще Replace в этой задаче?

**Comment by Carrybubbles** [comment]
C Replace я погорячился. Сюда лучше подойдет String.Trim();

**Comment by pavel-b-novikov** [comment]
То есть вы полагаете что Trim избавит вас от новых строк?

**Comment by Carrybubbles** [comment]
Ну он не избавил нас от лишних строк. А как сделать по-нормальному что-то идеи в голову не приходят, только костыли.

**Comment by Carrybubbles** [comment]
Убрал Trim

**Comment by pavel-b-novikov** [comment]
Криво и косо, но ладно
