### ISSUE TITLE
[Enigma] Работа с путями

### ISSUE THREAD

**Issue by pavel-b-novikov** [Carrybubbles/nsudotnet#7]
С путями файлов вы работаете неправильно

**Comment by Carrybubbles** [comment]
Заюзал class Path

**Comment by pavel-b-novikov** [comment]
Ну а Concat у вас по-прежнему от строки. Недоюзали.

**Comment by Carrybubbles** [comment]
Воспользовался String.Format()
`  var keyFileNameWithExtension = string.Format("{0}.key.txt", Path.GetFileNameWithoutExtension(_input));`

**Comment by pavel-b-novikov** [comment]
Ай, ладно. Ну хоть так.
